In [ ]:
import inaSpeechSegmenter.segmenter as ss
import os
from skimage.util import view_as_windows as vaw
import tempfile
from sidekit.frontend.io import read_wav
from sidekit.frontend.features import mfcc
import numpy as np
import pylab as pl
import warnings

In [75]:
medianame = './media/0021.mp3'
tmpdir = None
ffmpeg = 'ffmpeg'
from subprocess import Popen, PIPE
base, _ = os.path.splitext(os.path.basename(medianame))
with tempfile.TemporaryDirectory(dir=tmpdir) as tmpdirname:
    tmpwav = tmpdirname + '/' + base + '.wav'
    args = [ffmpeg, '-y', '-i', medianame, '-ar', '16000', '-ac', '1', tmpwav]
    p = Popen(args, stdout=PIPE, stderr=PIPE)
    output, error = p.communicate()
    assert p.returncode == 0, error
    sig, read_framerate, sampwidth = read_wav(tmpwav)
    print(sampwidth)
    sig *= (2**(15-sampwidth))
    sig = sig.astype(np.float32)
    _, loge, _, mspec = mfcc(sig, get_mspec=True)

2


In [76]:
npad = 0
if len(loge) < 68:
    warnings.warn('file is short. Recommended minimal length is sdf')
    npad = 68 - len(loge)
    mspec = np.concatenate((mspec, np.ones((npad, 24)) * np.NaN))
    loge = np.concatenate((loge, np.ones(npad) * np.NaN))
len(loge), loge, mspec

/home/ddoukhan/gitrepos/inaspeechsegmenterunittest/env/lib/python3.5/site-packages/ipykernel_launcher.py:3: UserWarning: file is short. Recommended minimal length is sdf
  This is separate from the ipykernel package so we can avoid doing imports until


(68, array([23.65635872, 23.5308876 , 23.50606728, 23.95367432, 24.93335152,
        27.24055481, 28.61566925, 28.63872337, 33.07403183, 38.89593506,
        39.59596634, 39.92473984, 39.96703339, 40.29489899, 40.44159698,
        40.45202255, 40.39542007, 40.52690887, 40.57311249, 40.40034866,
        40.10721588, 39.50094986, 38.72129822, 38.51928711, 37.85783005,
        36.41557312, 36.02762222, 35.76215744, 35.26826859, 35.22908401,
        35.45957184, 35.02663422, 34.07130432, 34.18313599, 33.79420853,
        32.42498779, 31.98526573, 27.70948219, 26.72745323, 26.39244843,
        26.17528534, 26.06599998, 26.04698563, 26.30700874, 27.58955574,
        38.09862137, 39.16085815, 41.02388   , 41.29766083, 41.11893082,
        40.01370621, 39.07500839, 37.44717026, 36.31087494, 35.08143997,
        33.91564941, 32.60082245, 31.18219948, 29.3219738 , 28.06219292,
        26.09040451, 25.30325508, 24.49750519, 23.92131805, 23.72994232,
        23.53020477,         nan,         nan])

In [77]:
ss._get_patches(mspec, 68, 2)

(array([[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],
 
        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],
 
        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],
 
        ...,
 
        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan,

In [42]:
loge = loge[:68]
mspec = mspec[:68,:]

In [43]:
mspec.shape

(68, 24)

In [49]:
ss._get_patches(mspec, 68, 2)[1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [50]:
loge

array([23.65635984, 23.53088785, 23.50606787, 23.95367392, 24.93335236,
       27.24055481, 28.6156694 , 28.63872279, 33.07403223, 38.89593532,
       39.59596498, 39.92474014, 39.96703281, 40.29489991, 40.44159842,
       40.45202094, 40.39542106, 40.52690773, 40.57311203, 40.40034816,
       40.1072162 , 39.50095095, 38.72129716, 38.5192862 , 37.85782956,
       36.41557155, 36.02762329, 35.76215554, 35.26826719, 35.22908467,
       35.45957139, 35.02663271, 34.0713043 , 34.18313631, 33.79420686,
       32.42498896, 31.98526655, 27.70948177, 26.72745243, 26.39244755,
       26.17528591, 26.06599945, 26.04698638, 26.30700851, 27.58955523,
       38.0986202 , 39.16085623, 41.02387835, 41.2976591 , 41.11892936,
       40.01370508, 39.07500877, 37.44717015, 36.31087484, 35.08143836,
       33.91564902, 32.600822  , 31.18219897, 29.32197461, 28.06219343,
       26.09040545, 25.30325551, 24.49750499, 23.92131739, 23.72994177,
       23.53020521, 23.72754197, 23.30309505])